language: ruby
sudo: false
before_install:
  - rm Gemfile.lock
  - mv Gemfile.travis Gemfile
  - mv test/dummy/config/database.yml.travis test/dummy/config/database.yml
script:
  - bundle exec rake db:create db:migrate test
env:
  - RAILS=4.2.0 DB=mysql
  - RAILS=4.2.0 DB=postgres
  - RAILS=4.2.0 DB=sqlite
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - jruby-9.0.0.0
  - jruby-9.1.0.0
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-9.0.0.0
    - rvm: jruby-9.1.0.0
addons:
  postgresql: 9.4
